


foo1:
	#$@
foo2:
	#$@


CXXFLAGS = asdasdlkjsad 
test: foo1 ; #$@ 1
test: foo2 ; #$@ 2
	#$@
	#${CXXFLAGS}













# asdasdsad







	#$@ Long way from home







   	FuckHimUp = Ha got em

	#$@ Even longer from home